<?php if (!defined('FORUM')) die();

if (file_exists($ext_info['path'].'/lang/'.$forum_user['language'].'.php'))
	require $ext_info['path'].'/lang/'.$forum_user['language'].'.php';
else
	require $ext_info['path'].'/lang/English.php';

$sat_bbcodes['img']['block'] = true;

$sat_bbcodes['img']['onclick'] = 'imgBut()';
$sat_bbcodes['img']['box'] = '<fieldset><div class="hidden"><input type="hidden" name="img_csrf_token" value="'.generate_form_token(forum_link('misc.php?action=satimgrec')).'" /></div><div class="img-box" id="img-box1"><label for="img-link">'.$lang_sat_image['linknote'].'</label> <input type="text" name="img-link" id="img-link" oninput="previewImage(this)">'.($forum_user['is_guest'] !=1 ? '<label for="img-upl">'.$lang_sat_image['or'].'</label> <input name="img-upl" id="img-upl" type="file" accept="image/*" onchange="uploadImage(this)">' : '').'</div><div class="img-box" id="img-box2"><label for="img-title">'.$lang_sat_image['titlenote'].'</label> <input type="text" name="img-title" id="img-title"></div><div class="img-box" id="img-box6"><label for="img-preview">'.$lang_sat_image['preview'].'</label><div id="img-preview"></div></div><div class="img-box" id="img-box3"><label>'.$lang_sat_image['floatnote'].'</label> <input type="radio" id="img-float1" name="img-float" value="none" checked="checked"><label for="img-float1"><img src="'.$ext_info['url'].'/img/1.png" title="'.$lang_sat_image['nofloat'].'"></label>&nbsp;<input type="radio" id="img-float2" name="img-float" value="left"><label for="img-float2"><img src="'.$ext_info['url'].'/img/2.png" title="'.$lang_sat_image['leftfloat'].'"></label>&nbsp;<input type="radio" id="img-float3" name="img-float" value="right"><label for="img-float3"><img src="'.$ext_info['url'].'/img/3.png" title="'.$lang_sat_image['rightfloat'].'"></label></div><div class="img-box" id="img-box4"><label for="img-width">'.$lang_sat_image['widthnote'].'</label> <input type="text" name="img-width" id="img-width" oninput="valnum($(this), \'positiveint\')"> <select id="pxpr"><option value="px">px</option><option value="pr">%</option></select></div><div class="img-box" id="img-box5"><label for="img-height">'.$lang_sat_image['heightnote'].'</label> <input type="text" name="img-height" id="img-height" oninput="valnum($(this), \'positiveint\')"> px</div></fieldset><div class="frm-buttons"><span class="submit primary"><input type="button" name="insertimg" value="'.$lang_sat_image['insertbutton'].'" onclick="insertImage()"></span></div>';